### PR TITLE
Support brackets in options

### PR DESCRIPTION
**Pull request by seishun**
Perhaps the parsed key doesn't need to include the brackets. 🤷

### CODE REVIEW

**Comment by keithamus** [comment]
This is awesome thanks for writing a test for this! I’ve been meaning to get round to this. I’ll try to get an implementation for next week unless you beat me to it 😜

**Comment by keithamus** [comment]
I think the output identifier should absolutely have brackets btw. Think of it from a perspective of a linter; we should be able to parse what might be valid grammar but violates higher level rules like the non-paren wrapped option being invalid.

**Comment by seishun** [comment]
But that's essentially delegating some parsing to the consumer. Could you clarify how leaving brackets in would help a linter?

FWIW Google's parser removes brackets but sets `is_extension` to `true`: https://github.com/protocolbuffers/protobuf/blob/88529f5017a3fd4a7cd4d666e541a3934e6491bd/src/google/protobuf/compiler/parser.cc#L1413

**Comment by keithamus** [comment]
Well the linter would need to know if it is an extension or not, so it can validate e.g. `java_package` vs `(java_package)`. A linter might want to validate the allowed non-extension option names so as to fail if provided an invalid non-extension name.

If we remove braces how does one determine `(foo.bar).baz = true` vs `(foo.bar.baz) = true`?

**Comment by seishun** [comment]
>Well the linter would need to know if it is an extension or not, so it can validate e.g. java_package vs (java_package). A linter might want to validate the allowed non-extension option names so as to fail if provided an invalid non-extension name.

The linter would know if it is an extension or not by checking the value of `is_extension` (or equivalent).

>If we remove braces how does one determine (foo.bar).baz = true vs (foo.bar.baz) = true?

The output identifier could be an array, similarly to `UninterpretedOption`. So `["foo.bar", "baz"]` vs `["foo.bar.baz"]`.

By the way, do you think a linter might want to enforce consistent use of single or double quotes in string literals?

**Comment by keithamus** [comment]
> By the way, do you think a linter might want to enforce consistent use of single or double quotes in string literals?

I do, which is why the string literal characters are retained in `.raw`

**Comment by keithamus** [comment]
@seishun I've added a commit which I think does the right thing, would be great to get a review from you - to see if you feel it will work.

**Comment by seishun** [comment]
I think it will work. But Option seems to be the same as FieldOption - why have both?

And I would move the `isExtension` field next to `key` since it's closely related.

**Comment by keithamus** [comment]
`Option` and `FieldOption` are mostly the same parser logic but subtly different - `Option` requires `option` keyword and suffix with `;` because its a statement, while `FieldOption` doesn't do those things. They're also useful to make a distinction when using the Visitor pattern, as you might want to scan for Options without having to see every FieldOption, or vice versa.

**Comment by seishun** [comment]
>Option and FieldOption are mostly the same parser logic but subtly different - Option requires option keyword and suffix with ; because its a statement, while FieldOption doesn't do those things.

This could be parametrized like in Google's parser: https://github.com/protocolbuffers/protobuf/blob/88529f5017a3fd4a7cd4d666e541a3934e6491bd/src/google/protobuf/compiler/parser.cc#L1454

>They're also useful to make a distinction when using the Visitor pattern, as you might want to scan for Options without having to see every FieldOption, or vice versa.

When would you want to scan for file options, message options, oneof options, enum options, service options and method options, but not field options?

**Pull request merged**
